;;; Copyright © 2025 Nikita Mitasov <mitanick@ya.ru>
(use-modules
 (guix utils)
 (gnu packages)
 (gnu packages wm)
 (guix transformations)
 (nongnu packages nvidia))
(define transform
  (options->transformation
   '((with-graft . "mesa=nvda"))))
(map transform
(map specification->package
     '("bat"
       "blueman"
       "btop"
       "curl"
       "emacs"
       "eog"
       "eza"
       "fastfetch"
       "fd"
       "file"
       "file-roller"
       "filezilla"
       "firefox"
       "font-awesome-nonfree"
       "font-google-noto"
       "fontforge"
       "fzf"
       "grim"
       "gnupg"
       "heroic-nvidia"
       "mwc"
       "swaybg"
       "kdenlive"
       "kitty"
       "krita"
       "ksh"
       "lazygit"
       "libreoffice"
       "mpv"
       "ncurses"
       "neovim"
       "nftables"
       "oils"
       "pavucontrol"
       "pcmanfm"
       "pipewire"
       "qbittorrent-enhanced"
       "quickshell"
       "remmina"
       "reuse"
       "ripgrep"
       "rofi-wayland"
       "starship"
       "telegram-desktop"
       "torbrowser"
       "unzip"
       "virt-manager"
       "waybar"
       "wireplumber"
       "wireplumber"
       "wl-clipboard"
       "wtype"
       "xdg-desktop-portal"
       "xdg-desktop-portal-wlr"
       "xdg-desktop-portal-gtk"
       "xdg-utils"
       "zip"
       "zoom"
       "zoxide"
       "zsh"
       "zsh-syntax-highlighting")))
